title: Donaldhan Blog
description: Just do it deeply...
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
github.repository_url: Donaldhan.github.io.git
repository: Donaldhan/Donaldhan.github.io.git


github.username: Donaldhan
iteye.username: donald-draper
jianshu.username: Donaldhan

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: "blog/page:num/"
